added comments

diff --git a/undear b/undear
--- a/undear
+++ b/undear
@@ -1,7 +1,8 @@
 #!/bin/bash
 
-# can run diff to see if 2 files are different
+# AUTHOR: JOSH NELSSON-SMITH
 
+# undear takes exactly 2 arguments, a flag and 
 if [ $# -eq 2 ]; then
     FLAG=$1
     DIR=$2
@@ -10,11 +11,15 @@ else
     exit 1
 fi
 
+# following are some regex's that match the various file types that we support the uncompression of
 GZIP_REGEX="(.+)\.tar\.gz$"
 BZIP2_REGEX="(.+)\.tar\.bz2$"
 COMPRESS_REGEX="(.+)\.tar\.Z$"
 TARFILE_REGEX="(.+)\.tar$"
 
+# here we unzip the file in the necessary way for each type, we also 
+# store the file path up until the filetype extension in the BASENAME variable, 
+# because we know after uncompression this will be the path to the uncompressed folder
 if [[ $DIR =~ $GZIP_REGEX ]]; then
     BASENAME=${BASH_REMATCH[1]}
     echo "dir is gzip file"
@@ -30,6 +35,7 @@ elif [[ $DIR =~ $COMPRESS_REGEX ]]; then
     echo "dir is compress file"
     uncompress -c $DIR > ${BASENAME}.tar
     tar -xf ${BASENAME}.tar
+    rm -rf ${BASENAME}.tar
 
 elif [[ $DIR =~ $TARFILE_REGEX ]]; then
     BASENAME=${BASH_REMATCH[1]}
@@ -41,27 +47,39 @@ else
     exit 1
 fi
 
-DUPE_FILE_PATH=${BASENAME}/duplicates
+# we know we store the duplicates at this path, 
+# we handle a failure to find the .duplicates file by exiting the program
+DUPE_FILE_PATH=${BASENAME}/.duplicates
+if [ ! -f $DUPE_FILE_PATH ]; then
+    echo "Dupe file does not exist, are you sure this archive was created with dear?"
+    rm -rf ${BASENAME}
+    exit 1
+fi
+
+# here we handle the different flags for undear
+# in each case we remove the .duplicates file after processing restoring the file 
+# as the user wishes
 case "${FLAG}" in
     -d)
         echo "d flag detected: deleting duplicate files"
-        rm -f ${DUPE_FILE_PATH}
+        rm -f ${DUPE_FILE_PATH} # the duplicates are already removed, so only need to remove .duplicates file
         exit 0
         ;;
     -l)
         echo "l flag detected: unarchiving dupes as soft links"
-        ./src/createSoftlinks.pl ${DUPE_FILE_PATH}
+        ./src/createSoftlinks.pl ${DUPE_FILE_PATH} # perl script creates soft links for us
         rm -f ${DUPE_FILE_PATH}
         exit 0
         ;; 
     -c)
         echo "c flag detected: unarchiving dupes as copies"
-        ./src/createCopies.pl ${DUPE_FILE_PATH}
+        ./src/createCopies.pl ${DUPE_FILE_PATH} # perl script restores copies for us
         rm -f ${DUPE_FILE_PATH}
         exit 0
         ;; 
     *)
         echo "Unsupported flag detected"
+        rm -rf ${BASENAME}
         exit 1
         ;;
 esac
